### ISSUE TITLE
Unable to add meta to blog when creating new site from front end

### ISSUE THREAD

**Issue by Buooy** [brasofilo/multisite-site-category#1]
Hi,

Thanks for the plugin, this is what im looking for.

However, although the plugin works well when i add a site from the backend, I cant seem to add the categories successfully from the front end.

The categories isnt captured in the database as the additional entry is not added into the blog_options table. 

Either the wpmu_new_blog action is not being triggered or the meta fields are not saved properly. Any ideaS?

**Comment by Buooy** [comment]
Hi,

I resolved the issue. I noticed in your plugin_setup(), you return if the user is not a network super admin. As such, any new user who signs up for a new site without login will be returned.

so you just need to change it to:

public function plugin_setup()
        {
            if( !is_admin() )
                add_action(
                        'signup_blogform', array( $this, 'signup_blogform_extra_field' )
                );

```
        $this->plugin_url  = plugins_url( '/', __FILE__ );
        $this->plugin_path = plugin_dir_path( __FILE__ );

        add_action(
                'wpmu_new_blog', array( $this, 'add_new_blog_field' )
        );
        add_filter(
                'add_signup_meta', array( $this, 'append_extra_field_as_meta' )
        );

       if( !is_network_admin() )
            return;

       add_action(
                'admin_print_scripts-site-new.php', array( $this, 'admin_scripts' )
        );
        add_action(
                'admin_footer-sites.php', array( $this, 'add_style' )
        );
        add_action(
                'manage_blogs_custom_column', array( $this, 'add_columns' ), 10, 2
        );
        add_action(
                'manage_sites_custom_column', array( $this, 'add_columns' ), 10, 2
        );
        add_filter(
                'wpmu_blogs_columns', array( $this, 'print_columns' )
        );
    }
```

**Comment by brasofilo** [comment]
Thanks for the contribution Buooy, I'll test and update the plugin asap.
:+1:
